apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-pre-prod-aoa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Beeze-Co/beeze-backend-aoa.git
    targetRevision: HEAD
    path: pre-prod/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false 