apiVersion: v2
name: jenkins
home: https://jenkins.io/
version: 3.1.8
appVersion: 2.263.3
description: Jenkins - Build great things at any scale! The leading open source automation server, Jenkins provides hundreds of plugins to support building, deploying and automating any project.
sources:
- https://github.com/jenkinsci/jenkins
- https://github.com/jenkinsci/docker-inbound-agent
- https://github.com/maorfr/kube-tasks
- https://github.com/jenkinsci/configuration-as-code-plugin
maintainers:
- name: maorfr
  email: maor.friedman@redhat.com
- name: torstenwalter
  email: mail@torstenwalter.de
- name: mogaal
  email: garridomota@gmail.com
- name: wmcdona89
  email: wmcdona89@gmail.com
- name: timja
  email: timjacomb1@gmail.com
icon: https://wiki.jenkins-ci.org/download/attachments/2916393/logo.png
annotations:
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins
    - name: Jenkins
      url: https://www.jenkins.io/
