apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pull-image-secret-generator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "delete"]